### ISSUE TITLE
TypeError: Cannot read property properties of undefined at module.exports

### ISSUE THREAD

**Issue by MohamedShawkyBayoumi** [AdeleD/react-paginate#231]
When I type `npm start` to serve the project on a localhost 

I found this error , How can I solve this ?

```
TypeError: Cannot read property 'properties' of undefined
    at module.exports (C:\Users\Mohamed Shawky\Desktop\react-paginate\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at C:\Users\Mohamed Shawky\Desktop\react-paginate\node_modules\webpack-cli\bin\webpack.js:60:27
    at Object.<anonymous> (C:\Users\Mohamed Shawky\Desktop\react-paginate\node_modules\webpack-cli\bin\webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-paginate@5.2.4 demo: `webpack --config demo/webpack.config.js --mode=development && node demo/data.js && node demo/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-paginate@5.2.4 demo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mohamed Shawky\AppData\Roaming\npm-cache\_logs\2018-09-25T17_23_29_257Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-paginate@5.2.4 start: `npm run demo`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-paginate@5.2.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mohamed Shawky\AppData\Roaming\npm-cache\_logs\2018-09-25T17_23_29_309Z-debug.log
PS C:\Users\Mohamed Shawky\Desktop\react-paginate>

```

**Comment by Nodios** [comment]
I have the same issue

**Comment by garyking** [comment]
I've got the same problem. The problem seems to have been introduced in a recent commit. I checked out the commit with the hash `8a6d8097f1f23ab2435ce60dedac5d3bfa843dad` and `yarn run demo` works fine now.

**Comment by SuperCipher** [comment]
I still have this similar issue.

npm run start

> react-paginate@5.2.4 start /Users/napatcharuphant/Pat/devSrc/testFile/react-paginate
> npm run demo


> react-paginate@5.2.4 demo /Users/napatcharuphant/Pat/devSrc/testFile/react-paginate
> webpack --config demo/webpack.config.js --mode=development && node demo/data.js && node demo/server.js

/Users/napatcharuphant/Pat/devSrc/testFile/react-paginate/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/Users/napatcharuphant/Pat/devSrc/testFile/react-paginate/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /Users/napatcharuphant/Pat/devSrc/testFile/react-paginate/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/Users/napatcharuphant/Pat/devSrc/testFile/react-paginate/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-paginate@5.2.4 demo: `webpack --config demo/webpack.config.js --mode=development && node demo/data.js && node demo/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-paginate@5.2.4 demo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/napatcharuphant/.npm/_logs/2018-11-01T11_00_33_748Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-paginate@5.2.4 start: `npm run demo`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-paginate@5.2.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/napatcharuphant/.npm/_logs/2018-11-01T11_00_33_780Z-debug.log

**Comment by AdeleD** [comment]
It was an issue with `webpack-cli`. I've upgraded the dependency, it should work now.
